### ISSUE TITLE
Scatter Plot appears differently on HTML file & Rstudio Notebook Output

### ISSUE THREAD

**Issue by sarahysaguirre** [Watts-College/cpp-526-spr-2022#16]
When attempting to knit my file, I noticed A LOT of my text/points were off. 

This is they way my plot looked when working on it in R studio:

![image](https://user-images.githubusercontent.com/97003912/151605853-314f146e-5162-4270-8709-20322cae1f18.png)

This is the way it looks on the HTML file and Notebook Output

![image](https://user-images.githubusercontent.com/97003912/151606072-440a8088-4c59-48f7-a04d-15b62c32498a.png)

This appears to be a common issue; 

https://github.com/rstudio/rstudio/issues/4521

Does anyone know of a possible fix?

**Comment by MonicaCable** [comment]
I'm not sure, but I think it's an issue with R more than it's an issue with HTML. I've noticed that if the monitor/window I'm looking at when I review the graph in R is larger/smaller that it will shift how clearly I can see the image. Your data looks fine, it's just the lines and text where there are issues, and everything looks like it's an issue vertically rather than horizontally. I would make sure that your points line up with the lines on the graph. Originally I had set positions and offset values, which also skewed my text. Maybe try removing those if they're in your code? I'm still playing with my colors but this worked pretty well for me:

# 1914 - US enters WWI
text(1914,                    # Add text
     1,
     "U.S. enters \nWorld War I.",
     col = "gray50",
     cex = 0.5,
     )

segments(x0 = 1914,           # Add line
         y0 = 1.3,
         x1 = 1914,
         y1 = mean(ave.so[year==1914]),
         col = "gray50",
         )

**Comment by asukajames** [comment]
@sarahysaguirre 
I have heard that this is a common issue and you just need to keep knitting to see if the position looks right!

**Comment by sarahysaguirre** [comment]
> I'm not sure, but I think it's an issue with R more than it's an issue with HTML. I've noticed that if the monitor/window I'm looking at when I review the graph in R is larger/smaller that it will shift how clearly I can see the image. Your data looks fine, it's just the lines and text where there are issues, and everything looks like it's an issue vertically rather than horizontally. I would make sure that your points line up with the lines on the graph. Originally I had set positions and offset values, which also skewed my text. Maybe try removing those if they're in your code? I'm still playing with my colors but this worked pretty well for me:
> 
> # 1914 - US enters WWI
> text(1914, # Add text 1, "U.S. enters \nWorld War I.", col = "gray50", cex = 0.5, )
> 
> segments(x0 = 1914, # Add line y0 = 1.3, x1 = 1914, y1 = mean(ave.so[year==1914]), col = "gray50", )

THANK YOU SO MUCH! This fixed my issue. I definitely over complicated my function. 

I personally used "steel blue" for the average text and line, "darkgray" for my text and ""gray85" for my segments. I feel like I've tried a ton of different grays but these looked closest. 

Thank you again!

**Comment by JPRayes** [comment]
I just realized this issue as well today and had to keep knitting my files each time I added code to make sure everything was lining up. Very time consuming!

**Comment by AndrewSchwarz145** [comment]
Did anyone find a solution to this? Or did it not matter for submitting the lab? I am having a similar problem with lab 4, the graph has some minor issues in appearance when changing the output to html_document.
