### ISSUE TITLE
Lab 2: Question 7

### ISSUE THREAD

**Issue by CarlyDeal** [Watts-College/cpp-526-spr-2022#2]
I'm struggling with question 7. For part 1, I  did:

these.means <- downtown$landuse =="Commercial" & downtown$amtdelinqt > "0"
> mean(these.means, na.rm=T)
[1] 0.06426735

However, I'm struggling with the second part and creating a subset.

**Comment by gmcirco** [comment]
Let me give you a hint, as your first answer is close but not entirely correct:

For the first part of the question, it is probably simpler to separate the data into a new dataframe with only commercial properties. This will make calculating the total number of commercial properties easier because you will start with the correct denominator (only commercial properties).

num. of delinquent commercial properties/num. of all commercial properties

You can accomplish this by doing something like:

`commercial <- downtown[downtown$landuse == "Commercial",]`

For question 2 you need to find out two things:

1. tax dollars owed by commercial properties
2. all tax dollars

Think about this question like the first one. You can first find out the `sum()` of all tax dollars owed and save it as an object, then  find out the total value of all tax dollars. After that, all you need to do is divide #1 by #2.

**Comment by droach7** [comment]
@gmcirco 

I am a little bit confused by your hint or how Carly's answer of 6.42% of commercial properties are delinquent on tax payments is wrong. 

I played around with this question a bit and tried doing it in the way you mentioned by creating a commercial properties dataframe and then determining the total number (209) and proportion of delinquent commercial properties (11.96%). However, when I tried generating a map from this data it didn't match the map in the lab instructions, which I have been using to assess whether I am doing things correctly. 

I played around some more, and the only way I could get the maps of Tax Delinquent Commercial Properties, and Tax Delinquent Non-Commercial Properties to match was by using the following code as the results in the map:

`result <- downtown$landuse == "Commercial" & downtown$amtdelinqt > 0`

`result <- downtown$landuse != "Commercial" & downtown$amtdelinqt > 0`

This was the same code Carly had said she used above.

**Could you please clarify why this is happening or which method/answer is correct?**

Listed below is my code when I was playing around with both methods:

```
df.commercial <- downtown[downtown$landuse == "Commercial", ] # New dataframe with only commercial properties
nrow(df.commercial) # Total number of commercial properties in downtown (209)
delinquent.commercial <- df.commercial$amtdelinqt >0 #Subset of commercial properties that are delinquent on taxes
sum(delinquent.commercial) # sum of delinquent commercial properties (25)
mean(delinquent.commercial) #proportion of delinquent commercial properties (11.96%)


doublecheck <- downtown$landuse == "Commercial" & downtown$amtdelinqt > 0
sum(doublecheck) # Sum is the same: 25
mean(doublecheck) # Mean is different at 6.4% as opposed to 11.96% calculated the other way
```

**Comment by gmcirco** [comment]
The second answer is not correct because the question is asking for:

> "tax-delinquent commercial properties over all commercial properties"

Your first answer works because the correct denominator is 209 (the number of commercial properties). You should notice that in your second answer, your variable `doublecheck` has a length of 389 which is ALL properties. The sum is the same because it has the same number of `TRUE` values, but you have too many `FALSE` values because you are including non-commercial properties. See my code example below. You can try it out yourself.

```
# how many commercial properties are there?
commercial <- downtown[downtown$landuse == "Commercial",]

# 209
nrow(commercial)

# how many TOTAL properties are there?

# 389
nrow(downtown)

# how many commercial properties are delinquent?

# 25
n_delinquent <- sum(commercial$amtdelinqt > 0)

# now calculate the proportion of commercial properties
# that are delinquent
# this is 25 / 209

# 0.119
n_delinquent / nrow(commercial)

# this is the incorrect way, because 389 
# is ALL properties, NOT just commercial

# 0.064
n_delinquent / nrow(downtown)

```

**Comment by droach7** [comment]
@gmcirco 

Ahhh, okay. That explanation helps me understand why the commercial data-frame should be used for determining proportion whilst the compound subset commands work for the map. Thanks for clarifying!

**Comment by mhagan2202** [comment]
@gmcirco 

Hey Gio, thanks for the input. I am also having trouble with the second part for question number 7. I am having trouble getting the sum of Commercial Tax that is owed. This is what I have thus far.... any additional help would be appreciated. Thank you

CommercialTaxOwed <- downtown[downtown$landuse == "Commercial" & 
                                downtown$amtdelinqt, ]

TotalTaxOwed <- sum(downtown$amtdelinqt)


CommercialTaxOwed/TotalTaxOwed

**Comment by gmcirco** [comment]
@mhagan2202 

You should think about it this way: First find out how much is owed by just commercial properties. You have the right idea, but need to adjust it a bit. Here's a few hints:

This will give you just commercial properties.

`commercial <- downtown[downtown$landuse == "Commercial",]`

This will give you the total tax owed by commercial properties

`CommercialTaxOwed<- sum(commercial$amtdelinqt)`

Now you just need to find out the total tax owed, and divide the commercial owed by total owed.

**Comment by mhagan2202** [comment]
@gmcirco 

I appreciate the quick response and thank you
