### ISSUE TITLE
Lab 4

### ISSUE THREAD

**Issue by CarlyDeal** [Watts-College/cpp-526-spr-2022#25]
Do we have to add this code for each team for their stats to appear:

# adding season stats for the team:
dat.one.team <- filter( Teams, name == team.name )
points( x=dat.one.team$yearID, y=dat.one.team$ave.so, 
        pch=20,  cex=1.2, col="goldenrod1", type="b" )

**Comment by CarlyDeal** [comment]
Main issue right now is getting the stats to appear when clicking on the team name from drop down box.

**Comment by AndrewSchwarz145** [comment]
You should only have to put the code in once, not for each team.  If the stats are not appearing when you click on a team in the drop down box, make sure the line: 
dat.one.team <- filter( Teams, name == team.name )

is located somewhere above the plot.new() line.  Sorry if this isn't helpful. Otherwise, I think the code looks fine.

**Comment by lilliau** [comment]
Hi Carly,
I was struggling with this too, but I found that the order of your code really matters in this one. Just be sure that you move a portion of the code from the template, below your plot code from Lab 3. So essentially your code would look like this:

# Template code provided - Part I
index <- which(Teams$yearID <= 2012 & Teams$yearID >= 1900)
Teams <- Teams[index, ]
index <- which(year <= 2012 & year >= 1900)
ave.so <- ave.so[index]
year <- year[index]
index <- which(league.year <= 2012 
               & league.year >= 1900)
league.ave <- league.ave[index]
league.year <- league.year[index]

# Your code from Lab 3:
plot.new()...etc.

# Template code provided - Part II
team.name <- input$my_team                 
dat.one.team <- filter(Teams,name == team.name)

# Team code that you posted
dat.one.team <- filter( Teams, name == team.name )
points( x=dat.one.team$yearID, y=dat.one.team$ave.so,
pch=20, cex=1.2, col="goldenrod1", type="b" 

# Team legend code
--------

You have to put the team code below your plot code so that it shows up over the plot. I hope this makes sense and it helps!

**Comment by mhagan2202** [comment]
if i try to just run selected line team.name <- input$my_team  it tells me that object 'input' not found which ultimately prevents me from calling the my_team identifier used in the selectinput chunk code. don't know if I need to download additional packages or add something else to my code but i'm running into the same issue. Any additional help would be appreciated. Thank you for your time @gmcirco

**Comment by gmcirco** [comment]
You need to hit "Run Document" to see any changes you make to your Shiny application. Because the input is reactive, it only has a value when the app is run.

**Comment by mhagan2202** [comment]
> You need to hit "Run Document" to see any changes you make to your Shiny application. Because the input is reactive, it only has a value when the app is run.

That did the trick, thank you

**Comment by CarlyDeal** [comment]
> Hi Carly, I was struggling with this too, but I found that the order of your code really matters in this one. Just be sure that you move a portion of the code from the template, below your plot code from Lab 3. So essentially your code would look like this:
> 
> # Template code provided - Part I
> index <- which(Teams$yearID <= 2012 & Teams$yearID >= 1900) Teams <- Teams[index, ] index <- which(year <= 2012 & year >= 1900) ave.so <- ave.so[index] year <- year[index] index <- which(league.year <= 2012 & league.year >= 1900) league.ave <- league.ave[index] league.year <- league.year[index]
> 
> # Your code from Lab 3:
> plot.new()...etc.
> 
> # Template code provided - Part II
> team.name <- input$my_team dat.one.team <- filter(Teams,name == team.name)
> 
> # Team code that you posted
> dat.one.team <- filter( Teams, name == team.name ) points( x=dat.one.team$yearID, y=dat.one.team$ave.so, pch=20, cex=1.2, col="goldenrod1", type="b"
> 
> # Team legend code
> You have to put the team code below your plot code so that it shows up over the plot. I hope this makes sense and it helps!

Thank you!! That made everything work!
