### ISSUE TITLE
Part 3 Question 3: Rates of Harm

### ISSUE THREAD

**Issue by JPRayes** [Watts-College/cpp-526-spr-2022#38]
I'm trying to mutate all collisions to create proportions but I keep getting errors:

dat %>%
  group_by(hour) %>%
  mutate(harm = Totalinjuries + Totalfatalities) %>%
  mutate(all_collisions = dat$Totalfatalities >= 0 & dat$Totalinjuries >= 0) %>%
  select(harm, hour, all_collisions) %>%
  count(harm, hour, all_collisions) %>%
  summarize(n = n()) %>%

Error: Problem with `mutate()` column `all_collisions`. i `all_collisions = dat$Totalfatalities >= 0 & dat$Totalinjuries >= 0`. i `all_collisions` must be size 388 or 1, not 28470. i The error occurred in group 1: hour = "00".

**Comment by gmcirco** [comment]
I'm not entirely sure what you are trying to work out here, but a few things to keep in mind:

When you use `mutate()` you do not need to refer to specific variables with `$`. Since they are piped in via `%>%` the `mutate()` function knows which ones you are referring to by name. 

I cleaned up your code and this will run, although your function for `all_collisions` will return a vector of `TRUE` because you are specifying a logical operator with `>=0` (also, specifying greater than or equal to zero will equal ALL the rows because there are no negative fatalities or injuries).

`dat %>%
mutate(harm = Totalinjuries + Totalfatalities,
       all_collisions = Totalfatalities >= 0 & Totalinjuries >= 0) %>%
select(harm, hour, all_collisions) %>%
count(harm, hour, all_collisions)`

What I think you want instead is the count and proportions by hour, if you look at the examples, you need to use `count()` to get the number of injuries and fatalities by hour. For example, try starting with:

`dat %>%
  count(hour, Totalinjuries, Totalfatalities)`
