### ISSUE TITLE
Lab 6: Step 3 - W Object not found

### ISSUE THREAD

**Issue by MonicaCable** [Watts-College/cpp-526-spr-2022#44]
I'm trying to identify the salary per win in part 3, and I'm getting the below error message:

**Error: Problem with `mutate()` column `salary.per.win.mutate`.
i `salary.per.win.mutate = total.salary/W`.
x object 'W' not found
i The error occurred in group 1: teamID = ANA.
Run `rlang::last_error()` to see where the error occurred.**

In Step 2 I saved the merged dataset as Combined, and when I look on the right I can see that the object W is listed in the dataset. I also was able to try to create the object salary.per.win without using the pipe operator and it worked fine, so I know that W is in the dataset Combined

**salary.per.win <- sum(Combined$salary.adj) / Combined$W**

But when I try to use the mutate function within the pipe, it gives me the object not found error. I've also tried reordering my summarize and mutate functions and the arguments in each to see if the order that they're in matters, but it hasn't gotten me anywhere. Code below:

**Combined %>% 
  group_by(teamID, yearID) %>% 
  summarize(total.salary = sum(salary.adj),
            players = n()) %>% 
  mutate(salary.per.win.mutate = total.salary/W,
         salary.per.100k = total.salary/100000)**

What am I missing? @gmcirco

**Comment by gmcirco** [comment]
A few issues here:

When you do `summarize` you will drop all columns not specified in the summarize function. So your `group_by %>% summarize` function will only retain `teamID`, `yearID`,  `total.salary`, and `players`. Rather than doing that, you should use `mutate` to retain all the other columns and then you can sum over them later. This way you will keep the `W` column in the data as well.
