### ISSUE TITLE
Lab 6: Step 3

### ISSUE THREAD

**Issue by CarlyDeal** [Watts-College/cpp-526-spr-2022#46]
Having trouble with step 3. I get an error, not sure what I'm missing.

salary.per.win <- sum(datcombined$salary.adj) / datcombined$W

datcombined %>%
  group_by(teamID, yearID) %>%
  mutate(salaryper100k = salary.per.win / 100000)

**Comment by MonicaCable** [comment]
Not 100% confident on this, but I think it's because the object salary.per.win isn't part of your dataset datcombined. When you use the %>% pipe operator, you don't have to name which dataset you're looking for before the $ because in the first line you specified that you're always looking inside of datcombined. If you look on the right side of your screen you should see that you salary.per.win is listed separately as a Value, where all the datasets are listed as Data.

If salary.adj and W are already part of your dataset datcombined, maybe try using mutate in two steps:

datcombined %>%
   group_by(teamID, yearID) %>%
   mutate(salary.per.win=sum(salary.adj)/W,
               salaryper100k = salary.per.win / 100000)

**Comment by asukajames** [comment]
I did step by step like Monica and got the correct number. 
 
mutate (cost.per.win.step = team.budget / W)%>%
mutate (cost.per.win = cost.per.win.step / 100000)
