### ISSUE TITLE
Lab 2: Challenge Question 3

### ISSUE THREAD

**Issue by CarlyDeal** [Watts-College/cpp-526-spr-2022#5]
I'm having issues with challenge question 3. Everything I'm trying gives me the total number of commercial parcels that have an assessed value over 0. Not sure what to do to add up all of those values? I'm assuming what I'm doing now is just adding up all the trues, thus getting 209.

commercial <-downtown[downtown$landuse =="Commercial", ]
value <- sum(commercial$assessedval >0)
sum(value)
[1] 209

x<- downtown$assessedland >0 & downtown$landuse =="Commercial"
sum(x, na.rm=T)
[1] 209

totalvalue <-downtown[downtown$assessedval >0, ]
sum(totalvalue$landuse =="Commercial")
[1] 209

I've tried a lot of different things but can't seem to get the right answer!

**Comment by gmcirco** [comment]
You have the right idea. You filtered out commercial properties correctly, the only issue is how you are getting the results. 

`value <- sum(commercial$assessedval >0)`

Will give you the total number of `TRUE` and `FALSE` values because you have a logical test in there `> 0`.

If you want the sum of the value, you just need to remove the logical test.

`value <- sum(commercial$assessedval )`
