### ISSUE TITLE
Dashboard Project Initial Errors

### ISSUE THREAD

**Issue by JPRayes** [Watts-College/cpp-526-spr-2022#55]
So I'm trying to load the Dashboard before I input any of my own code and I keep getting errors. I've been trying to correct them by updating packages, etc. but I continue to run into more errors:

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘xfun’ 0.25 is being loaded, but >= 0.27 is required

Error in checkboxGroupInput("days", label = h3("Day of Week"), choices = list(Monday = "Mon",  : 
  could not find function "checkboxGroupInput"

Anybody else getting these errors or know how to fix them?

**Comment by JPRayes** [comment]
Another Error: 

[1] 127
Warning message:
In system(paste0("rmarkdown::run \"", input, "\"")) :
  'rmarkdown::run' not found

**Comment by MonicaCable** [comment]
I'm not sure if this is it or not, but make sure instead of hitting Run All (Ctrl + Alt + R) you're instead clicking on the button that says Run Document. Because it's interactive it's running on Shiny, and Shiny can't perform the interactive tasks in the R Console.

If that doesn't work, I'd try shutting down R, redownloading the template, and then hitting Run Document. I don't think there's any install.packages in this one but make sure that if there are you put a # in front of it so it doesn't keep trying to install it, I had that happen when I was working on my code through project.

**Comment by gmcirco** [comment]
@JPRayes 

Make sure you are rendering the document and not trying to run the code chunks individually. Since this is a Shinyapp, you have to render the entire document (this is similar to the interactive baseball example).

**Comment by JPRayes** [comment]
@gmcirco I’ve restarted R several times and made sure the appropriate packages are installed. I click “Run Document” and continue to get this message:

[1] 127
Warning message:
In system(paste0("rmarkdown::run "", input, """)) :
'rmarkdown::run' not found


I even reloaded a new Rmd file and still get the same error.

**Comment by JPRayes** [comment]
I Figured out the problem: https://stackoverflow.com/questions/68436632/rmarkdownrender-not-found-error-when-knit

Had to install a package "tinytex", then had to update the version of "rlang" and install "Rtools".

**Comment by gmcirco** [comment]
Glad you figured it out!
