### ISSUE TITLE
Adding surface conditions

### ISSUE THREAD

**Issue by lilliau** [Watts-College/cpp-526-spr-2022#60]
I am trying to add surface condition counts for a check box widget and I'm not quite sure how to add them together. I see the template code (below) and trying to do the same for surface conditions but I'm not sure how to add them together. In the given code it says that when "Alcohol" and "No Apparent Influence" is checked, then the result is the count of "Alcohol", etc.
dat <- 
  dat %>% 
  mutate( d2.substance = case_when( AlcoholUse_Drv2 == "Alcohol" & 
                                      DrugUse_Drv2 == "No Apparent Influence" ~ "Alcohol", 
                                    AlcoholUse_Drv2 == "No Apparent Influence" & 
                                      DrugUse_Drv2 == "Drugs" ~ "Drugs", 
                                    AlcoholUse_Drv2 == "Alcohol" & 
                                      DrugUse_Drv2 == "Drugs" ~ "Alcohol and Drugs", 
                                    AlcoholUse_Drv2 == "No Apparent Influence" & 
                                      DrugUse_Drv2 == "No Apparent Influence" ~ "No Apparent Influence"))

I'm not quite sure how to do that with surface conditions. I came up with similar code, but nothing is coming out on my map:
dat <- 
  dat %>% 
  mutate( surface.cond = case_when(SurfaceCondition == "Dry" & 
                                     SurfaceCondition == "Wet" ~ "Dry and Wet", 
                                   SurfaceCondition == "Dry" & 
                                     SurfaceCondition == "Water Standing Moving" ~ "Dry and Water Standing Moving",
                                    SurfaceCondition == "Dry" & 
                                      SurfaceCondition == "Unknown" ~ "Dry and Unknown",
                                    SurfaceCondition == "Wet" &
                                      SurfaceCondition == "Water Standing Moving" ~ "Wet and Water Standing Moving",
                                    SurfaceCondition == "Wet" &
                                      SurfaceCondition == "Unknown" ~ "Wet and Unknown",
                                    SurfaceCondition == "Water Standing Moving" &
                                      SurfaceCondition == "Unknown" ~ "Water Standing Moving and Unknown"))

I am wanting to add these through checkboxes because I am listing them in conjunction with weather (radio buttons). I am using this code to filter:

d100 <-
    dat %>%
    filter(Weather == input$weather1,
           surface.cond == input$surface1)

Thanks in advance for the help!

**Comment by gmcirco** [comment]
The issue is with your recoding of the SurfaceCondition variable. The way you are trying to recode it will not work because you are specifying a conditional statement that is not possible. For example, you have:

`case_when(SurfaceCondition == "Dry" & SurfaceCondition == "Wet" ~ "Dry and Wet"`

This says: if SurfaceCondition is Dry AND if SurfaceCondition is Wet, recode to "Dry and Wet"

Look at the variable attributes, this is impossible because the variable can have only one value! It can only be dry OR wet, and can't be both. Therefore, this will return an `NA` value. That is why you are not seeing anything. I would suggest either using the default categories, or recoding the remaining ones (the few categories that are not `Dry`, `Wet`, or `Unknown Water` into a single "other" category.
